#ifndef ENUMS_HPP
#define ENUMS_HPP

enum class Ranges
{
  LEVELS = 5,
  LEVEL_ONE_WIDTH = 20,
  LEVEL_ONE_HEIGHT = 10,
  DROP_RATE = 5,
  AMOUNT_OF_ARMOR = 5,
  IDLE_ZONE_WIDTH = 9,
  IDLE_ZONE_HEIGHT = 7,
  LEVEL_TWO_WIDTH = 20,
  LEVEL_TWO_HEIGHT = 20,
  LEVEL_THREE_WIDTH = 20,
  LEVEL_THREE_HEIGHT = 20,
  LEVEL_FOUR_WIDTH = 30,
  LEVEL_FOUR_HEIGHT = 20,
  LEVEL_FIVE_WIDTH = 20,
  LEVEL_FIVE_HEIGHT = 20
};

enum class AnimationsSize
{
  AMOUNT_OF_SOLDIER_IDLE_FRAMES = 6,
  AMOUNT_OF_ORC_IDLE_FRAMES = 6,
  SOLDIER_IDLE_W = 15,
  SOLDIER_IDLE_H = 18,
  SOLDIER_IDLE_H_EXECEPTION = 19,
  SOLDIER_ATTACK_ONE_W = 19,
  SOLDIER_ATTACK_ONE_H = 24,
  SOLDIER_ATTACK_TWO_W = 20,
  SOLDIER_ATTACK_TWO_H = 23,
  SOLDIER_ATTACK_THREE_AND_FOUR_W = 34,
  SOLDIER_ATTACK_THREE_AND_FOUR_H = 20,
  SOLDIER_ATTACK_FIVE_W = 22,
  SOLDIER_ATTACK_FIVE_H = 18,
  SOLDIER_WALKING_W = 15, // 1 , 2, 4, 5, 6
  SOLDIER_WALKING_H = 18,
  SOLDIER_WALKING_H_EXCEPTION = 17, // 3,7

  SOLDIER_SPECIAL_ABILITY_ONE_W = 15,
  SOLDIER_SPECIAL_ABILITY_ONE_H = 18,

  SOLDIER_SPECIAL_ABILITY_TWO_W = 19,
  SOLDIER_SPECIAL_ABILITY_TWO_H = 22,

  SOLDIER_SPECIAL_ABILITY_THREE_W = 18,
  SOLDIER_SPECIAL_ABILITY_THREE_H = 20,

  SOLDIER_SPECIAL_ABILITY_FOUR_W = 28,
  SOLDIER_SPECIAL_ABILITY_FOUR_H = 23,

  SOLDIER_SPECIAL_ABILITY_FIVE_W = 28,
  SOLDIER_SPECIAL_ABILITY_FIVE_H = 17,

  SOLDIER_SPECIAL_ABILITY_SIX_W = 28,
  SOLDIER_SPECIAL_ABILITY_SIX_H = 18,


  SOLDIER_DEATH_ONE_W = 15,
  SOLDIER_DEATH_ONE_H = 18,
  SOLDIER_DEATH_TWO_W = 16,
  SOLDIER_DEATH_TWO_H = 16,
  SOLDIER_DEATH_THREE_W = 15,
  SOLDIER_DEATH_THREE_H = 14,
  SOLDIER_DEATH_FOUR_W = 19,
  SOLDIER_DEATH_FOUR_H = 10,


  ORC_PLATED_IDLE_W = 25,
  ORC_PLATED_IDLE_H = 19,
  ORC_PLATED_IDLE_EXCEPTION_H = 20,
  ORC_PLATED_WALK_W = 25,
  ORC_PLATED_WALK_H = 19,
  ORC_PLATED_WALK_EXCEPTION = 24,

  ORC_PLATED_ATTACK_ONE_W = 25,
  ORC_PLATED_ATTACK_ONE_H = 19,
  ORC_PLATED_ATTACK_TWO_W = 31,
  ORC_PLATED_ATTACK_TWO_H = 19,
  ORC_PLATED_ATTACK_THREE_W = 26,
  ORC_PLATED_ATTACK_THREE_H = 19,
  ORC_PLATED_ATTACK_FOUR_FIVE_W = 22,
  ORC_PLATED_ATTACK_FOUR_FIVE_H = 18,
  ORC_PLATED_ATTACK_SIX_W = 37,
  ORC_PLATED_ATTACK_SIX_H = 18,
  ORC_PLATED_ATTACK_SEVEN_W = 38,
  ORC_PLATED_ATTACK_SEVEN_H = 18,
  ORC_PLATED_ATTACK_EIGHT_W = 38,
  ORC_PLATED_ATTACK_EIGHT_H = 18,

  ORC_PLATED_HURT_W = 26,
  ORC_PLATED_HURT_H = 19,

  ORC_PLATED_DEATH_ONE_W = 25,
  ORC_PLATED_DEATH_ONE_H = 19,
  ORC_PLATED_DEATH_TWO_W = 28,
  ORC_PLATED_DEATH_TWO_H = 20,
  ORC_PLATED_DEATH_THREE_W = 40,
  ORC_PLATED_DEATH_THREE_H = 16,
  ORC_PLATED_DEATH_FOUR_W = 41,
  ORC_PLATED_DEATH_FOUR_H = 11,

  ORC_ELITE_IDLE_W = 28,
  ORC_ELITE_IDLE_H = 23,
  ORC_ELITE_IDLE_H_EXCEPTION = 24,
  ORC_ELITE_WALK_W = 28,
  ORC_ELITE_WALK_H = 23,
  ORC_ELITE_WALK_H_EXCEPTION = 22,
  ORC_ELITE_HURT_W = 29,
  ORC_ELITE_HURT_H = 23,

  ORC_ELITE_DEATH_ONE_W = 28,
  ORC_ELITE_DEATH_ONE_H = 23,
  ORC_ELITE_DEATH_TWO_W = 36,
  ORC_ELITE_DEATH_TWO_H = 25,
  ORC_ELITE_DEATH_THREE_W = 45,
  ORC_ELITE_DEATH_THREE_H = 21,
  ORC_ELITE_DEATH_FOUR_W = 34,
  ORC_ELITE_DEATH_FOUR_H = 15,

  ORC_ELITE_DEATH_FIRST_ATTACK_ONE_W = 28,
  ORC_ELITE_DEATH_FIRST_ATTACK_ONE_H = 23,

  ORC_ELITE_DEATH_FIRST_ATTACK_TWO_W = 29,
  ORC_ELITE_DEATH_FIRST_ATTACK_TWO_H = 24,

  ORC_ELITE_DEATH_FIRST_ATTACK_THREE_W = 27,
  ORC_ELITE_DEATH_FIRST_ATTACK_THREE_H = 29,

  ORC_ELITE_DEATH_FIRST_ATTACK_FOUR_W = 41,
  ORC_ELITE_DEATH_FIRST_ATTACK_FOUR_H = 30,

  ORC_ELITE_DEATH_FIRST_ATTACK_FIVE_W = 36,
  ORC_ELITE_DEATH_FIRST_ATTACK_FIVE_H = 30,
  

  ORC_ELITE_DEATH_FIRST_ATTACK_SIX_W = 21,
  ORC_ELITE_DEATH_FIRST_ATTACK_SIX_H = 28,

  ORC_ELITE_DEATH_FIRST_ATTACK_SEVEN_W = 20,
  ORC_ELITE_DEATH_FIRST_ATTACK_SEVEN_H = 29,

  ORC_ELITE_DEATH_SECOND_ATTACK_ONE_W = 28,
  ORC_ELITE_DEATH_SECOND_ATTACK_ONE_H = 23,

  ORC_ELITE_DEATH_SECOND_ATTACK_TWO_W = 39,
  ORC_ELITE_DEATH_SECOND_ATTACK_TWO_H = 25,

  ORC_ELITE_DEATH_SECOND_ATTACK_THREE_W = 52,
  ORC_ELITE_DEATH_SECOND_ATTACK_THREE_H = 26,

  ORC_ELITE_DEATH_SECOND_ATTACK_FOUR_W = 45,
  ORC_ELITE_DEATH_SECOND_ATTACK_FOUR_H = 26,

  ORC_ELITE_DEATH_SECOND_ATTACK_FIVE_W = 45,
  ORC_ELITE_DEATH_SECOND_ATTACK_FIVE_H = 24,

  ORC_ELITE_DEATH_SECOND_ATTACK_SIX_W = 39,
  ORC_ELITE_DEATH_SECOND_ATTACK_SIX_H = 25,

  ORC_ELITE_DEATH_SECOND_ATTACK_SEVEN_W = 29,
  ORC_ELITE_DEATH_SECOND_ATTACK_SEVEN_H = 30,

  ORC_ELITE_THIRD_ATTACK_ONE_W = 28,
  ORC_ELITE_THIRD_ATTACK_ONE_H = 23,

  ORC_ELITE_THIRD_ATTACK_TWO_W = 20,
  ORC_ELITE_THIRD_ATTACK_TWO_H = 33,

  ORC_ELITE_THIRD_ATTACK_THREE_W = 22,
  ORC_ELITE_THIRD_ATTACK_THREE_H = 40,

  ORC_ELITE_THIRD_ATTACK_FOUR_W = 28,
  ORC_ELITE_THIRD_ATTACK_FOUR_H = 37,

  ORC_ELITE_THIRD_ATTACK_FIVE_W = 38,
  ORC_ELITE_THIRD_ATTACK_FIVE_H = 45,

  ORC_ELITE_THIRD_ATTACK_SIX_W = 39,
  ORC_ELITE_THIRD_ATTACK_SIX_H = 43,

  ORC_ELITE_THIRD_ATTACK_SEVEN_W = 39,
  ORC_ELITE_THIRD_ATTACK_SEVEN_H = 21,

  ORC_ELITE_THIRD_ATTACK_EIGHT_W = 28,
  ORC_ELITE_THIRD_ATTACK_EIGHT_H = 24,

  ORC_IDLE_W = 22,
  ORC_IDLE_H = 15,
  ORC_IDLE_H_EXCEPTION = 16,
  ORC_ATTACKING_ONE_BOTH = 19,
  ORC_ATTACKING_TWO_W = 19,
  ORC_ATTACKING_TWO_H = 24,
  ORC_ATTACKING_THREE_W = 28,
  ORC_ATTACKING_THREE_H = 26,
  ORC_ATTACKING_FOUR_W = 28,
  ORC_ATTACKING_FOUR_H = 20,
  ORC_ATTACKING_FIVE_W = 26,
  ORC_ATTACKING_FIVE_H = 19,
  ORC_WALK_FIRST_W = 21,
  ORC_WALK_H = 15,
  ORC_WALK_SECOND_W = 22,
  ORC_WALK_THIRD_W = 22,
  ORC_WALK_H_EXCEPTION = 14,
  ORC_WALK_FOURTH_W = 21,
  ORC_WALK_FIFTH_W = 22,
  ORC_WALK_SIXTH_W = 22,
  ORC_WALK_SEVENTH_W = 22,
  SOLDIER_HURT_ALL_H = 18,
  SOLDIER_HURT_ALL_W = 16,
  ORC_HURT_ALL_W = 23,
  ORC_HURT_ALL_H = 15,
  ORC_DEAD_FIRST_W = 22,
  ORC_DEAD_FIRST_H = 15,
  ORC_DEAD_SECOND_W = 26,
  ORC_DEAD_SECOND_H = 14,
  ORC_DEAD_THIRD_W = 28,
  ORC_DEAD_THIRD_H = 17,
  ORC_DEAD_FOURTH_W = 29,
  ORC_DEAD_FOURTH_H = 11,

  CANDLESTICK_BOTH = 16,
  NEEDLES_BOTH = 16,
  LADDERS_BOTH = 16,
  TORCHES_BOTH = 16,
  SHOPKEEPER_BOTH = 16,
  BANNER_BOTH = 16,
  CHEST_BOTH = 16, // check this out
  BOX_BOTH = 16,
  KEYS_BOTH = 16,
  VERTICAL_FLAMETHROWER_W = 16,
  VERTICAL_FLAMETHROWER_H = 32,
  HORIZONTAL_FLAMETHROWER_W = 32,
  HORIZONTAL_FLAMETHROWER_H = 16,
  ARROW_TRAP_W = 16,
  ARROW_TRAP_H = 32,
  HOURGLASS_BOTH = 32
};

enum class AnimationState
{
  SOLDIER_IDLE,
  SOLDIER_ATTACK,
  SOLDIER_WALKING,
  SOLDIER_HURT,
  SOLDIER_DEATH,
  SOLDIER_SPECIAL_ABILITY,

  // New !
  ORC_PLATED_IDLE,
  ORC_PLATED_WALK,
  ORC_PLATED_ATTACK,
  ORC_PLATED_HURT,
  ORC_PLATED_DEATH,

  ORC_ELITE_IDLE,
  ORC_ELITE_WALK,
  ORC_ELITE_HURT,
  ORC_ELITE_DEATH,
  ORC_ELITE_FIRST_ATTACK,
  ORC_ELITE_SECOND_ATTACK,
  ORC_ELITE_THIRD_ATTACK,



  ORC_IDLE,
  ORC_ATTACKING,
  ORC_WALKING,
  ORC_HURT,
  ORC_DEATH,
  CANDLESTICK_BURNING,
  NEEDLES_MOVING_FROM_GROUND,
  LADDERS_ARROW_MOVING,
  TORCHES_FLAME_HORIZONTAL_WALL,
  SHOP_KEEPER_IDLE,
  BANNER,
  TORCHES_VERTICAL_WALL,
  CHEST_MINI_ANIM,
  CHEST_MINI_OPENING,
  CHEST_BIG_ANIM,
  CHEST_BIG_OPENINIG,
  BOX_SMALL_WOOD,
  BOX_BIG_WOOD,
  BOX_SMALL_IRON,
  BOX_BIG_IRON,
  SILVER_KEY,
  GOLD_KEY,
  VERTICAL_FLAMETHROWER,
  HORIZONTAL_FLAMETHROWER,
  ARROW_TRAP_ANIMATION,
  HOURGLASS_ROTATING
};

enum class UI
{
  INVALID_TEXT,
  PLAYER_HP,
  ENEMY_HP,
  INVENTORY,
  SHOP,
  SHOP_INVENTORY_PLAYER_TEXT,
  SHOP_PRICE_POT,
  SHOP_PRICE_MUSHROOM,
  SHOP_PRICE_RUBY_RING,
  SHOP_PRICE_SAPPHIRE_RING,
  SHOP_PRICE_GOLD_SWORD,
  SHOP_PRICE_BIG_GOLD_SWORD,
  INVENTORY_TEXT_FOR_MONEY,
  INVENTORY_TEXT_FOR_HP,
  INVENTORY_TEXT_FOR_ATTACK,
  INVENTORY_TEXT_FOR_INVENTORY_DECLARATION
};

enum class ArmorSlot
{
  SWORD,
  RING_ONE,
  RING_TWO,
  TRINKET_ONE,
  TRINKET_TWO
};

enum class Values
{
  NO_VALUE = 0,
  MUSHROOM = 1,
  POTION = 2,
  RING = 10,
  TRINKET = 10,
  SWORD = 5
};

enum class Grid
{
  NO_TERRAIN = -1,
  RESERVED = 999,

  FLOOR_NEW_ONE = 66,
  FLOOR_NEW_TWO = 67,
  FLOOR_NEW_THREE = 68,
  FLOOR = 0,

  WALL_HORIZONTAL_NEW_ONE = 69,
  WALL_HORIZONTAL_NEW_TWO = 70,
  WALL_HORIZONTAL_NEW_THREE = 71,
  WALL_HORIZONTAL_NEW_DOWNSIDE = 72,
  WALL_HORIZONTAL = 1,

  WALL_VERTICAL_NEW = 73, // 2 squares 
  WALL_VERTICAL_EDGE_DOWNSIDE = 74, 
  WALL_VERTICAL_NEW_DOWNSIDE_WITH_PADDING = 78,
  WALL_VERTICAL_LEFT_CLASSIC_PADDING = 76, // 1 rectangle
  WALL_VERTICAL_NEW_WITH_PADDING = 77, // 2 squares
  WALL_VERTICAL = 2,

  WALL_CORNER_TOP_LEFT = 75,
  WALL_CORNER_TOP_RIGHT = 79,

  CHARACTER_SOLD = 3,
  CHARACTER_ORC = 4,
  TRASURE = 5,
  HEARTH_FULL = 6,
  HEARTH_HALF = 7,
  HEARTH_EMPTY = 8,
  COIN = 9,
  MUSHROOM = 10,
  RING_SAPPHIRE_GOLD = 11,
  HEALTH_POT = 12,
  RING_RUBY = 13,
  RING_SAPPHIRE = 14,
  STONE_SWORD = 15,
  GOLD_SWORD = 16,
  BIG_GOLD_SWORD = 17,
  TRINKET_RUBY = 18,
  TRINKET_RUBY_GOLD = 19,
  TRINKET_SAPPHIRE = 20,
  DOORS_VERTICAL = 21,
  CANDLESTICK = 22,
  NEEDLES = 23,
  LADDERS = 24,
  TORCH_HORIZONTAL_WALL = 25,
  SKELETON_HEAD = 26,
  SKELETON_BONES = 27,
  SHOPKEEPER = 28,
  BANNER = 29,
  SMALL_COBWEB = 30,
  BIG_COBWEB = 31,
  DOORS_HORIZONTAL_LEFT_WING = 32,
  DOORS_HORIZONTAL_RIGHT_WING = 33,
  TORCH_VERTICAL_LEFT_SIDE = 34,
  TORCH_VERTICAL_RIGHT_SIDE = 35,
  CHEST = 36,
  CHEST_MINI = 37,
  BOX_IRON_SMALL = 38,
  BOX_IRON_BIG = 39,
  BOX_WOOD_SMALL = 40,
  BOX_WOOD_BIG = 41,
  SILVER_KEY = 42,
  GOLD_KEY = 43,
  FLAMETHROWER_VERTICAL = 44,
  FLAMETHROWER_HORIZONTAL = 45,
  ARROW_TRAP = 46,
  CHAIN_ONE = 47,
  CHAIN_TWO = 48,

  // Size (w x h) in pixels
  V_WALL_W = 7,
  V_WALL_H = 16,
  V_WALL_W_WITH_PADING = 16,
  H_WALL_W = 16,
  H_WALL_H = 16,
  CORNER_WALL_BOTH = 16,
  FLOOR_W = 16,
  FLOOR_H = 16,
  TILE_SIZE = 64,
  SOLDIER_W = 15,
  SOLDIER_H = 19,
  ORC_W = 22,
  ORC_H = 15,
  ALL_HEARTHS_W = 13,
  ALL_HEARTHS_H = 10,
  COIN_BOTH = 10,
  HEALTH_POT_W = 10,
  HEALTH_POT_H = 12,
  MUSHROOM_W = 12,
  MUSHROOM_H = 14,
  RING_SAPPHIRE_GOLD_BOTH = 11, // All rings have 11x11
  TRINKETS_BOTH = 12,
  SWORDS_ALL = 12,
  DOORS_VERTICAL_H = 16,
  DOORS_VERTICAL_W = 6,
  BOTH_SKELLYS = 16,
  COBWEB_BOTH = 16,
  DOORS_HORIZONTAL_BOTH = 16,
  CHAINS_BOTH = 16
};

enum class Movement
{
  UPWARDS = 0,
  DOWNWARDS = 1,
  LEFT = 2,
  RIGHT = 3
};

enum class Detection
{
  NOTHING_DETECTED,
  DETECTED_UP,
  DETECTED_DOWN,
  DETECTED_LEFT,
  DETECTED_RIGHT
};


enum class Errors
{
  SUCCESS = 0,
  FAILED = 1,
  // =======

  E_WRONG_ARGC = 2,
  E_WRONG_ARGV = 3,
  E_SDL_WINDOW = 4,
  E_SDL_INIT = 5,
  E_SDL_RENDERER = 6,
  E_FONT_LOAD_FAIL = 7
};


const int SCALING_FACTOR_THREE = 3;
const int SCALING_FACTOR_TWO = 2;
const int SCALING_FACTOR_FOUR = 4;

const int cell_both_dimensions = 15 * SCALING_FACTOR_THREE;
const int rows = 7;
const int rows_shop = 2;
const int columns = 5;
const int columns_shop = 3;
const int vertical_gap = 1 * SCALING_FACTOR_THREE;
const int horizontal_gap = 2 * SCALING_FACTOR_THREE;


const int beginning_of_grid_X = 772;
const int beginning_of_grid_Y = 329;

const int items_inventory_x = 124 * SCALING_FACTOR_THREE;
const int items_inventory_y = 36 * SCALING_FACTOR_THREE;

const int sword_x_axis_inventory = 14 * SCALING_FACTOR_THREE; // 14
const int sword_y_axis_inventory = 41 * SCALING_FACTOR_THREE; // 40

const int armor_x_axis_inventory = 86 * SCALING_FACTOR_THREE; // 86
const int armor_y_axis_inventory = 16 * SCALING_FACTOR_THREE; // 15

const int vertical_gap_shop_items_to_sell = 13 * SCALING_FACTOR_THREE;
const int horizontal_gap_shop_items_to_sell = 16 * SCALING_FACTOR_THREE;

const int items_to_sell_shop_x = 20 * SCALING_FACTOR_THREE;
const int items_to_sell_shop_y = 83 * SCALING_FACTOR_THREE;

const float ONE_SECOND = 1000.0f;
const int ENEMY_SENSOR_RADIUS = 3;


const int ORC_ATTACKING_Y_OFFSET = 5 * SCALING_FACTOR_THREE;
const int ORC_DEATH_Y_OFFSET = 4 * SCALING_FACTOR_THREE;
const int CANDLESTICK_Y_OFFSET = 10;
const int NEEDLES_Y_OFFSET = 10;
const int TORCHES_VERTICAL_X_OFFSET = 2 * SCALING_FACTOR_FOUR;


const int INVENTORY_TEXT_DECLARATION_X = 126 * SCALING_FACTOR_THREE;
const int INVENTORY_TEXT_DECLARATION_Y = 20 * SCALING_FACTOR_THREE;

const int INVENTORY_PLAYER_HP_X = 14 * SCALING_FACTOR_THREE;
const int INVENTORY_PLAYER_HP_Y = 88 * SCALING_FACTOR_THREE;

const int INVENTORY_COIN_AND_ATTACK_POWER_X = INVENTORY_PLAYER_HP_X;

const int INVENTROY_TEXT_VERTICAL_GAP = 20 * SCALING_FACTOR_THREE;

const int COIN_Y_AT_PRICES = 1 * SCALING_FACTOR_THREE;
const int SHOP_INVENTORY_ITEMS_X_DIFFERENCE = 1 * SCALING_FACTOR_THREE;
const int SHOP_INVENTORY_ITEMS_Y_DIFFERENCE = 3 * SCALING_FACTOR_THREE;




#endif