import pygame

from ..constants import PADDING_FOR_EVERY_SIDE, MATRIX_X_POSITION

EVERY_BOX_WIDTH = MATRIX_X_POSITION - (2 * PADDING_FOR_EVERY_SIDE) # Left padding Right padding 
EVERY_BOX_HEIGHT = 50

BFS_X = PADDING_FOR_EVERY_SIDE
BFS_Y = PADDING_FOR_EVERY_SIDE

DFS_X = PADDING_FOR_EVERY_SIDE
DFS_Y = BFS_Y + EVERY_BOX_HEIGHT + PADDING_FOR_EVERY_SIDE

A_STAR_X = PADDING_FOR_EVERY_SIDE
A_STAR_Y = DFS_Y + EVERY_BOX_HEIGHT + PADDING_FOR_EVERY_SIDE

DJIKSTRA_X = PADDING_FOR_EVERY_SIDE
DJIKSTRA_Y = A_STAR_Y + EVERY_BOX_HEIGHT + PADDING_FOR_EVERY_SIDE



class RenderingFunctionsContainer:
  def __init__(self):
    pass


  def renderUI(self):
    pass


