#ifndef OFFSETS_UI_HPP
#define OFFSETS_UI_HPP


enum class Offsets
{
  LOGIN_USERNAME = 0,
  LOGIN_PASSWORD = 1,
  REGISTRATION_USERNAME = 2,
  REGISTRATION_PASSWORD = 3,
  REGISTRATION_PASSWORD_CONFIRMATION = 4
};


#endif