#ifndef OFFSETS_UI_HPP
#define OFFSETS_UI_HPP


enum class Offsets
{

  // [LOGIN STATE OFFSETS]
  LOGIN_USERNAME = 0,
  LOGIN_PASSWORD = 1,
  REGISTRATION_USERNAME = 2,
  REGISTRATION_PASSWORD = 3,
  REGISTRATION_PASSWORD_CONFIRMATION = 4,

  // [Character Overview Offsets]
  CHAROVERVIEW_PLACEHOLDER_ONE = 5,
  CHAROVERVIEW_PLACEHOLDER_TWO = 6,
  CHAROVERVIEW_PLACEHOLDER_THREE = 7,
  CHAROVERVIEW_PLACEHOLDER_FOUR = 8,
  CHAROVERVIEW_PLACEHOLDER_FIVE = 9,
  CHAROVERVIEW_PLACEHOLDER_SIX = 10,
  CHAROVERVIEW_PLACEHOLDER_SEVEN = 11

};





#endif