#ifndef OFFSETS_UI_HPP
#define OFFSETS_UI_HPP


enum class Offsets
{
  LOGIN_USERNAME = 0,
  LOGIN_PASSWORD = 1,
  REGISTRATION_USERNAME = 2,
  REGISTRATION_PASSWORD = 3,
  REGISTRATION_PASSWORD_CONFIRMATION = 4
};

enum class BitMapOffsets
{
  LETTER_A = 0,
  LETTER_B = 1,
  LETTER_C = 2,
  LETTER_D = 3,
  LETTER_E = 4,
  LETTER_F = 5,
  LETTER_G = 6,
  LETTER_H = 7,
  LETTER_I = 8,
  LETTER_J = 9,
  LETTER_K = 10,
  LETTER_L = 11,
  LETTER_M = 12,
  LETTER_N = 13,
  LETTER_O = 14,
  LETTER_P = 15,
  LETTER_Q = 16,
  LETTER_R = 17,
  LETTER_S = 18,
  LETTER_T = 19,
  LETTER_U = 20,
  LETTER_V = 21,
  LETTER_W = 22,
  LETTER_X = 23,
  LETTER_Y = 24,
  LETTER_Z = 25,

  LETTER_a = 26,
  LETTER_b = 27,
  LETTER_c = 28,
  LETTER_d = 29,
  LETTER_e = 30,
  LETTER_f = 31,
  LETTER_g = 32,
  LETTER_h = 33,
  LETTER_i = 34,
  LETTER_j = 35,
  LETTER_k = 36,
  LETTER_l = 37,
  LETTER_m = 38,
  LETTER_n = 39,
  LETTER_o = 40,
  LETTER_p = 41,
  LETTER_q = 42,
  LETTER_r = 43,
  LETTER_s = 44,
  LETTER_t = 45,
  LETTER_u = 46,
  LETTER_v = 47,
  LETTER_w = 48,
  LETTER_x = 49,
  LETTER_y = 50,
  LETTER_z = 51,

  NUMBER_0 = 52,
  NUMBER_1 = 53,
  NUMBER_2 = 54,
  NUMBER_3 = 55,
  NUMBER_4 = 56,
  NUMBER_5 = 57,
  NUMBER_6 = 58,
  NUMBER_7 = 59,
  NUMBER_8 = 60,
  NUMBER_9 = 61
};



#endif